schema_version = "1.0.0"

id = "spreadsheet_import"
name = "Spreadsheet Import"
version = "0.4.0"
tagline = "Import data to spreadsheet for use with geometry nodes"
type = "add-on"
blender_version_min = "4.2.0"
maintainer = "Simon Broggi <simon.broggi@insert-coin.ch>"
tags = ["Import-Export", "Geometry Nodes"]
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Load CSV and JSON files from disk"
