schema_version = "1.0.0"

id = "blender_spreadsheet_import"
name = "Spreadsheet Data Importer"
version = "0.2.0"
tagline = "Import data to spreadsheet for use with geometry nodes"
type = "add-on"
blender_version_min = "3.3.0"
maintainer = "Simon Broggi <email@address.com>"
tags = ["Import-Export"]
license = [
  "SPDX:GPL-3.0-or-later",
]
